In [10]:
import numpy as np

# read npy file

# read npy file
hmatrix_g1d = np.load('hmatrix_g1d.npy')
hmatrix_r1d = np.load('hmatrix_r1d.npy')
print(np.where(hmatrix_g1d == 255))
print(np.where(hmatrix_r1d == 255))


(array([544, 576, 608, 640, 672]),)
(array([ 81, 111, 112, 113, 143, 144, 175]),)


In [11]:

hmatrix_g1d = np.load('hmatrix_g1d.npy')
hmatrix_r1d = np.load('hmatrix_r1d.npy')
print(np.where(hmatrix_g1d == 255))
print(np.where(hmatrix_r1d == 255))

(array([ 81, 111, 112, 113, 143, 144, 174, 175]),)
(array([544, 576, 608, 640]),)
